create table if not exists public.site_settings (
  id integer primary key default 1 check (id = 1),
  sections_visibility jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.site_settings
  add column if not exists sections_visibility jsonb not null default '{}'::jsonb,
  add column if not exists updated_at timestamptz not null default timezone('utc', now());

drop trigger if exists sync_site_section_visibility_from_site_settings
on public.site_settings;

drop function if exists public.sync_site_section_visibility_from_site_settings();

drop table if exists public.site_section_visibility;

insert into public.site_settings (id, sections_visibility)
values (
  1,
  '{
    "header": true,
    "hero": true,
    "agent": true,
    "services": true,
    "properties": true,
    "why": true,
    "testimonials": true,
    "blog": true,
    "cta": true,
    "inquiry": true,
    "footer": true
  }'::jsonb
)
on conflict (id) do nothing;

update public.site_settings
set
  sections_visibility =
    '{
      "header": true,
      "hero": true,
      "agent": true,
      "services": true,
      "properties": true,
      "why": true,
      "testimonials": true,
      "blog": true,
      "cta": true,
      "inquiry": true,
      "footer": true
    }'::jsonb || coalesce(sections_visibility, '{}'::jsonb),
  updated_at = timezone('utc', now())
where id = 1;

create table public.site_section_visibility (
  id integer generated by default as identity primary key,
  section text not null unique,
  visibility boolean not null default true,
  updated_at timestamptz not null default timezone('utc', now())
);

with section_defaults(id, section) as (
  values
    (1, 'header'),
    (2, 'hero'),
    (3, 'agent'),
    (4, 'services'),
    (5, 'properties'),
    (6, 'why'),
    (7, 'testimonials'),
    (8, 'blog'),
    (9, 'cta'),
    (10, 'inquiry'),
    (11, 'footer')
),
existing_visibility as (
  select
    visibility.key as section,
    case
      when jsonb_typeof(visibility.value) = 'boolean'
        then visibility.value = 'true'::jsonb
      else true
    end as visibility
  from public.site_settings
  cross join lateral jsonb_each(public.site_settings.sections_visibility) as visibility(key, value)
  where public.site_settings.id = 1
),
ordered_sections as (
  select
    section_defaults.id,
    section_defaults.section,
    coalesce(existing_visibility.visibility, true) as visibility
  from section_defaults
  left join existing_visibility
    on existing_visibility.section = section_defaults.section

  union all

  select
    row_number() over (order by existing_visibility.section)
      + (select count(*) from section_defaults) as id,
    existing_visibility.section,
    existing_visibility.visibility
  from existing_visibility
  where not exists (
    select 1
    from section_defaults
    where section_defaults.section = existing_visibility.section
  )
)
insert into public.site_section_visibility (id, section, visibility, updated_at)
select
  ordered_sections.id,
  ordered_sections.section,
  ordered_sections.visibility,
  timezone('utc', now()) as updated_at
from ordered_sections
order by ordered_sections.id;

create or replace function public.sync_site_section_visibility_from_site_settings()
returns trigger
language plpgsql
as $$
begin
  insert into public.site_section_visibility (section, visibility, updated_at)
  select
    visibility.key as section,
    case
      when jsonb_typeof(visibility.value) = 'boolean'
        then visibility.value = 'true'::jsonb
      else true
    end as visibility,
    timezone('utc', now()) as updated_at
  from jsonb_each(coalesce(new.sections_visibility, '{}'::jsonb)) as visibility(key, value)
  on conflict (section) do update
  set
    visibility = excluded.visibility,
    updated_at = excluded.updated_at;

  delete from public.site_section_visibility
  where section not in (
    select visibility.key
    from jsonb_each(coalesce(new.sections_visibility, '{}'::jsonb)) as visibility(key, value)
  );

  return new;
end;
$$;

create trigger sync_site_section_visibility_from_site_settings
after insert or update of sections_visibility
on public.site_settings
for each row
when (new.id = 1)
execute function public.sync_site_section_visibility_from_site_settings();

alter table public.site_settings enable row level security;
alter table public.site_section_visibility enable row level security;

drop policy if exists "Public read site settings" on public.site_settings;
create policy "Public read site settings"
on public.site_settings
for select
to anon, authenticated
using (true);

drop policy if exists "Temporary public update site settings" on public.site_settings;
create policy "Temporary public update site settings"
on public.site_settings
for update
to anon, authenticated
using (id = 1)
with check (id = 1);

drop policy if exists "Public read site section visibility" on public.site_section_visibility;
create policy "Public read site section visibility"
on public.site_section_visibility
for select
to anon, authenticated
using (true);

drop policy if exists "Temporary public insert site section visibility" on public.site_section_visibility;
create policy "Temporary public insert site section visibility"
on public.site_section_visibility
for insert
to anon, authenticated
with check (true);

drop policy if exists "Temporary public update site section visibility" on public.site_section_visibility;
create policy "Temporary public update site section visibility"
on public.site_section_visibility
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "Temporary public delete site section visibility" on public.site_section_visibility;
create policy "Temporary public delete site section visibility"
on public.site_section_visibility
for delete
to anon, authenticated
using (true);
